# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'CV', folder: 'pages', file: 'cv.html'}
- {name: 'Photography', folder: 'pages', file: 'photography.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/inof8or'}
- {icon: 'facebook', link: 'https://www.facebook.com/Paul.Beaudet'}
- {icon: 'instagram', link: 'https://instagram.com/inof8or'}
- {icon: 'envelope', link: 'mailto:inof8or@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
